version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  app:
    container_name: app
    build: docker/php
    ports:
      - 9000:9000
    volumes:
    - ./:/var/www
    - ~/.composer:/root/.composer


